name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: write # ✅ needed for pushing version tags
  pages: write
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  version:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # ✅ needed to fetch tags

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate CalVer with daily counter
        run: |
          DATE=$(date +'%Y.%m.%d')   # e.g. 2025.10.05

          # Find latest tag for today
          LATEST_TAG=$(git tag --list "v$DATE.*" | sort -V | tail -n1)

          if [ -z "$LATEST_TAG" ]; then
            COUNT=0
          else
            COUNT=$(echo $LATEST_TAG | awk -F. '{print $4}')
            COUNT=$((COUNT + 1))
          fi

          VERSION="$DATE.$(printf "%02d" $COUNT)"
          echo "New version: $VERSION"

          # Update package.json
          jq --arg v "$VERSION" '.version=$v' package.json > tmp.json && mv tmp.json package.json

          git add package.json
          git commit -m "chore(release): $VERSION [skip ci]" || echo "No changes to commit"
          git tag "v$VERSION"
          git push origin main --tags

  build:
    runs-on: ubuntu-latest
    needs: version # ✅ only runs if versioning succeeds
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build with Parcel
        run: npm run build

      - name: Upload build output
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download build output
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: List dist files
        run: ls -R dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
          commit_message: "Deploy site from GitHub Actions"
